# ----
# Site

title: Brain Imaging Laboratory
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Brain Imaging Laboratory
author:
  name: Gaspare Galati
  email: gaspare.galati@uniroma1.it
  twitter: gaglab_
social:
  name: Brain Imaging Laboratory
  links:
    - https://bil.psi.uniroma1.it

# -----
# Build

timezone: CET

collections:
  staff:
    _hide_content: true
    sort_by: order
    output: true
  alumni:
    _hide_content: true
    sort_by: order
    output: true

paginate: 10
paginate_path: "/news/:num/"
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  - scope:
      path: ""
      type: "staff"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-github-metadata
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# GitHub Pages
repository: sapienza-brain-imaging-lab/sapienza-brain-imaging-lab.github.io

# -----------
# CloudCannon

_select_data:
  social_icons:
    - Facebook
    - Instagram
    - Twitter
    - YouTube
    - RSS

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window
